// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADxM7VxUQniLLHmmJlzuh-KvfL5gcnPA0',
    appId: '1:104507924666:web:119ea77a448a17b1d6e283',
    messagingSenderId: '104507924666',
    projectId: 'icsmartchair',
    authDomain: 'icsmartchair.firebaseapp.com',
    databaseURL: 'https://icsmartchair-default-rtdb.firebaseio.com',
    storageBucket: 'icsmartchair.appspot.com',
    measurementId: 'G-4CSJQC0Z8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWc6SOCUDM87U7EiNxU7tcewP6gfmKeH0',
    appId: '1:104507924666:android:7577f30c5cf67d16d6e283',
    messagingSenderId: '104507924666',
    projectId: 'icsmartchair',
    databaseURL: 'https://icsmartchair-default-rtdb.firebaseio.com',
    storageBucket: 'icsmartchair.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADxM7VxUQniLLHmmJlzuh-KvfL5gcnPA0',
    appId: '1:104507924666:web:c873d8536e5d4c56d6e283',
    messagingSenderId: '104507924666',
    projectId: 'icsmartchair',
    authDomain: 'icsmartchair.firebaseapp.com',
    databaseURL: 'https://icsmartchair-default-rtdb.firebaseio.com',
    storageBucket: 'icsmartchair.appspot.com',
    measurementId: 'G-708E1TCVZH',
  );
}
